In [132]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans


Desarrollo Pregunta 4 / Parte I

In [133]:
# Sin escalar las variables, describa tres iteraciones del algoritmo K-means para k = 2. 
# Use los centroides C1 = (47.5, 37.5, 21.8) y C2 = (53.2, 22.4, 75.3).

# datos sin escalar
X = np.array([[10, 4, 50],
              [8, 99, 31],
              [34, 44, 86],
              [9, 50, 57],
              [46, 77, 75],
              [68, 30, 14],
              [80, 25, 40],
              [50, 35, 60]])

# Centroides iniciales
C = np.array([[47.5, 37.5, 21.8],
              [53.2, 22.4, 75.3]])
    

In [134]:
# Función para calcular la distancia euclidiana
def euclidean_distance(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

# Función para asignar cada observación al centroide más cercano
def assign_clusters(X, C):
    clusters = []
    for x in X:
        distancia = [euclidean_distance(x, c) for c in C]
        cluster = np.argmin(distancia)
        clusters.append(cluster)
    return np.array(clusters)

# Función para calcular los nuevos centroides
def update_centroids(X, clusters, num_clusters):
    centroides = []
    for i in range(num_clusters):
        cluster_points = X[clusters == i]
        centroide = np.mean(cluster_points, axis=0)
        centroides.append(centroide)
    return np.array(centroides)


In [135]:
# Algoritmo K-means
num_clusters = 2
for iteracion in range(3):
    # Asignar observaciones a los centroides más cercanos
    clusters = assign_clusters(X, C)

    # Calcular nuevos centroides
    C = update_centroids(X, clusters, num_clusters)

    # Imprimir resultados con 2 decimales
    print(f"Iteration {iteracion + 1}:")
    print("Clusters:", clusters)
    print("Centroids:", np.round(C, 1))
    print()

Iteration 1:
Clusters: [1 0 1 0 1 0 0 1]
Centroids: [[41.2 51.  35.5]
 [35.  40.  67.8]]

Iteration 2:
Clusters: [1 0 1 1 1 0 0 1]
Centroids: [[52.  51.3 28.3]
 [29.8 42.  65.6]]

Iteration 3:
Clusters: [1 0 1 1 1 0 0 1]
Centroids: [[52.  51.3 28.3]
 [29.8 42.  65.6]]

